// Well-known events the builder can search. Names, places and the usual month only — dates change every
// year, so the athlete types the date. Anything not listed is typed in by hand.
import type { RaceDistance } from "../athlete";

export interface CatalogEvent { name: string; location: string; type: RaceDistance; month: number } // month 1–12

const M = { Jan: 1, Feb: 2, Mar: 3, Apr: 4, May: 5, Jun: 6, Jul: 7, Aug: 8, Sep: 9, Oct: 10, Nov: 11, Dec: 12 };
const e = (name: string, location: string, type: RaceDistance, month: keyof typeof M): CatalogEvent => ({ name, location, type, month: M[month] });

export const EVENTS: CatalogEvent[] = [
  // full-distance triathlon
  e("IRONMAN Texas", "The Woodlands, TX, USA", "140.6", "Apr"),
  e("IRONMAN St. George", "St. George, UT, USA", "140.6", "May"),
  e("IRONMAN Lake Placid", "Lake Placid, NY, USA", "140.6", "Jul"),
  e("IRONMAN Wisconsin", "Madison, WI, USA", "140.6", "Sep"),
  e("IRONMAN Maryland", "Cambridge, MD, USA", "140.6", "Sep"),
  e("IRONMAN Chattanooga", "Chattanooga, TN, USA", "140.6", "Sep"),
  e("IRONMAN California", "Sacramento, CA, USA", "140.6", "Oct"),
  e("IRONMAN Florida", "Panama City Beach, FL, USA", "140.6", "Nov"),
  e("IRONMAN Arizona", "Tempe, AZ, USA", "140.6", "Nov"),
  e("IRONMAN Cozumel", "Cozumel, Mexico", "140.6", "Nov"),
  e("IRONMAN Mont-Tremblant", "Mont-Tremblant, QC, Canada", "140.6", "Aug"),
  e("IRONMAN Canada", "Penticton, BC, Canada", "140.6", "Aug"),
  e("IRONMAN Frankfurt", "Frankfurt, Germany", "140.6", "Jun"),
  e("IRONMAN Hamburg", "Hamburg, Germany", "140.6", "Jun"),
  e("IRONMAN Austria", "Klagenfurt, Austria", "140.6", "Jun"),
  e("IRONMAN Switzerland", "Thun, Switzerland", "140.6", "Jul"),
  e("IRONMAN Vitoria-Gasteiz", "Vitoria-Gasteiz, Spain", "140.6", "Jul"),
  e("IRONMAN Copenhagen", "Copenhagen, Denmark", "140.6", "Aug"),
  e("IRONMAN Kalmar", "Kalmar, Sweden", "140.6", "Aug"),
  e("IRONMAN Tallinn", "Tallinn, Estonia", "140.6", "Aug"),
  e("IRONMAN Wales", "Tenby, Wales, UK", "140.6", "Sep"),
  e("IRONMAN Italy Emilia-Romagna", "Cervia, Italy", "140.6", "Sep"),
  e("IRONMAN Barcelona", "Calella, Spain", "140.6", "Oct"),
  e("IRONMAN Portugal-Cascais", "Cascais, Portugal", "140.6", "Oct"),
  e("IRONMAN South Africa", "Port Elizabeth, South Africa", "140.6", "Mar"),
  e("IRONMAN New Zealand", "Taupō, New Zealand", "140.6", "Mar"),
  e("IRONMAN Australia", "Port Macquarie, NSW, Australia", "140.6", "May"),
  e("IRONMAN Cairns", "Cairns, QLD, Australia", "140.6", "Jun"),
  e("IRONMAN Western Australia", "Busselton, WA, Australia", "140.6", "Dec"),
  e("IRONMAN Brazil", "Florianópolis, Brazil", "140.6", "May"),
  e("IRONMAN World Championship", "Kailua-Kona, HI, USA", "140.6", "Oct"),
  e("Challenge Roth", "Roth, Germany", "140.6", "Jul"),
  // half-distance triathlon
  e("IRONMAN 70.3 Oceanside", "Oceanside, CA, USA", "70.3", "Apr"),
  e("IRONMAN 70.3 St. George", "St. George, UT, USA", "70.3", "May"),
  e("IRONMAN 70.3 Texas", "Galveston, TX, USA", "70.3", "Apr"),
  e("IRONMAN 70.3 Eagleman", "Cambridge, MD, USA", "70.3", "Jun"),
  e("IRONMAN 70.3 Boulder", "Boulder, CO, USA", "70.3", "Jun"),
  e("IRONMAN 70.3 Lake Placid", "Lake Placid, NY, USA", "70.3", "Sep"),
  e("IRONMAN 70.3 Augusta", "Augusta, GA, USA", "70.3", "Sep"),
  e("IRONMAN 70.3 Chattanooga", "Chattanooga, TN, USA", "70.3", "May"),
  e("IRONMAN 70.3 Santa Cruz", "Santa Cruz, CA, USA", "70.3", "Sep"),
  e("IRONMAN 70.3 Indian Wells", "La Quinta, CA, USA", "70.3", "Dec"),
  e("IRONMAN 70.3 Arizona", "Tempe, AZ, USA", "70.3", "Oct"),
  e("IRONMAN 70.3 Florida", "Haines City, FL, USA", "70.3", "Apr"),
  e("IRONMAN 70.3 Mont-Tremblant", "Mont-Tremblant, QC, Canada", "70.3", "Jun"),
  e("IRONMAN 70.3 Dubai", "Dubai, UAE", "70.3", "Mar"),
  e("IRONMAN 70.3 Marbella", "Marbella, Spain", "70.3", "May"),
  e("IRONMAN 70.3 Barcelona", "Calella, Spain", "70.3", "May"),
  e("IRONMAN 70.3 Kraichgau", "Kraichgau, Germany", "70.3", "Jun"),
  e("IRONMAN 70.3 Zell am See-Kaprun", "Zell am See, Austria", "70.3", "Aug"),
  e("IRONMAN 70.3 Nice", "Nice, France", "70.3", "Sep"),
  e("IRONMAN 70.3 Cascais", "Cascais, Portugal", "70.3", "Sep"),
  e("IRONMAN 70.3 Mallorca", "Alcúdia, Spain", "70.3", "May"),
  e("IRONMAN 70.3 Swansea", "Swansea, Wales, UK", "70.3", "Jul"),
  e("IRONMAN 70.3 Sunshine Coast", "Mooloolaba, QLD, Australia", "70.3", "Sep"),
  e("IRONMAN 70.3 World Championship", "varies by year", "70.3", "Sep"),
  e("Challenge Cancún", "Cancún, Mexico", "70.3", "Nov"),
  // olympic / sprint
  e("Escape from Alcatraz Triathlon", "San Francisco, CA, USA", "olympic", "Jun"),
  e("Chicago Triathlon", "Chicago, IL, USA", "olympic", "Aug"),
  e("New York City Triathlon", "New York, NY, USA", "olympic", "Jul"),
  e("Malibu Triathlon", "Malibu, CA, USA", "olympic", "Sep"),
  e("Hamburg World Triathlon", "Hamburg, Germany", "olympic", "Jul"),
  e("London Triathlon", "London, UK", "olympic", "Aug"),
  e("Blenheim Palace Triathlon", "Woodstock, UK", "sprint", "Jun"),
  e("Noosa Triathlon", "Noosa, QLD, Australia", "olympic", "Nov"),
  // marathons
  e("Boston Marathon", "Boston, MA, USA", "marathon", "Apr"),
  e("London Marathon", "London, UK", "marathon", "Apr"),
  e("Berlin Marathon", "Berlin, Germany", "marathon", "Sep"),
  e("Chicago Marathon", "Chicago, IL, USA", "marathon", "Oct"),
  e("New York City Marathon", "New York, NY, USA", "marathon", "Nov"),
  e("Tokyo Marathon", "Tokyo, Japan", "marathon", "Mar"),
  e("Sydney Marathon", "Sydney, Australia", "marathon", "Aug"),
  e("Paris Marathon", "Paris, France", "marathon", "Apr"),
  e("Valencia Marathon", "Valencia, Spain", "marathon", "Dec"),
  e("Amsterdam Marathon", "Amsterdam, Netherlands", "marathon", "Oct"),
  e("Rotterdam Marathon", "Rotterdam, Netherlands", "marathon", "Apr"),
  e("Frankfurt Marathon", "Frankfurt, Germany", "marathon", "Oct"),
  e("Hamburg Marathon", "Hamburg, Germany", "marathon", "Apr"),
  e("Vienna City Marathon", "Vienna, Austria", "marathon", "Apr"),
  e("Los Angeles Marathon", "Los Angeles, CA, USA", "marathon", "Mar"),
  e("Houston Marathon", "Houston, TX, USA", "marathon", "Jan"),
  e("Philadelphia Marathon", "Philadelphia, PA, USA", "marathon", "Nov"),
  e("Marine Corps Marathon", "Arlington, VA, USA", "marathon", "Oct"),
  e("Twin Cities Marathon", "Minneapolis, MN, USA", "marathon", "Oct"),
  e("California International Marathon", "Sacramento, CA, USA", "marathon", "Dec"),
  e("Big Sur International Marathon", "Big Sur, CA, USA", "marathon", "Apr"),
  e("San Francisco Marathon", "San Francisco, CA, USA", "marathon", "Jul"),
  e("Honolulu Marathon", "Honolulu, HI, USA", "marathon", "Dec"),
  e("Lisbon Marathon", "Lisbon, Portugal", "marathon", "Oct"),
  e("Porto Marathon", "Porto, Portugal", "marathon", "Nov"),
  e("Munich Marathon", "Munich, Germany", "marathon", "Oct"),
  e("Stockholm Marathon", "Stockholm, Sweden", "marathon", "Jun"),
  e("Copenhagen Marathon", "Copenhagen, Denmark", "marathon", "May"),
  e("Athens Authentic Marathon", "Athens, Greece", "marathon", "Nov"),
  e("Cape Town Marathon", "Cape Town, South Africa", "marathon", "Oct"),
  // half marathons
  e("Great North Run", "Newcastle, UK", "half", "Sep"),
  e("New York City Half", "New York, NY, USA", "half", "Mar"),
  e("Berlin Half Marathon", "Berlin, Germany", "half", "Apr"),
  e("Valencia Half Marathon", "Valencia, Spain", "half", "Oct"),
  e("Lisbon Half Marathon", "Lisbon, Portugal", "half", "Mar"),
  e("Copenhagen Half Marathon", "Copenhagen, Denmark", "half", "Sep"),
  e("Rock 'n' Roll San Diego", "San Diego, CA, USA", "half", "Jun"),
  e("Brooklyn Half", "Brooklyn, NY, USA", "half", "May"),
  e("Bay to Breakers", "San Francisco, CA, USA", "10k", "May"),
  e("Peachtree Road Race", "Atlanta, GA, USA", "10k", "Jul"),
  e("Comrades Marathon", "Durban–Pietermaritzburg, South Africa", "ultra", "Jun"),
  e("Western States 100", "Olympic Valley, CA, USA", "ultra", "Jun"),
  e("UTMB", "Chamonix, France", "ultra", "Aug"),
  // cycling
  e("L'Étape du Tour", "France (Tour de France stage)", "gran_fondo", "Jul"),
  e("Maratona dles Dolomites", "Alta Badia, Italy", "gran_fondo", "Jul"),
  e("Mallorca 312", "Mallorca, Spain", "gran_fondo", "Apr"),
  e("Gran Fondo New York", "New York, NY, USA", "gran_fondo", "May"),
  e("Levi's GranFondo", "Santa Rosa, CA, USA", "gran_fondo", "Oct"),
  e("Haute Route Alps", "French Alps", "gran_fondo", "Aug"),
  e("Cape Town Cycle Tour", "Cape Town, South Africa", "gran_fondo", "Mar"),
  e("Ride London-Essex 100", "London, UK", "century", "May"),
  e("Seattle to Portland (STP)", "Seattle, WA, USA", "century", "Jul"),
  e("Death Ride", "Markleeville, CA, USA", "century", "Jul"),
  e("Marin Century", "Marin County, CA, USA", "century", "Aug"),
  e("Unbound Gravel", "Emporia, KS, USA", "gran_fondo", "Jun"),
  // open water
  e("Alcatraz Sharkfest Swim", "San Francisco, CA, USA", "swim_ow", "Aug"),
  e("Bosphorus Cross-Continental Swim", "Istanbul, Türkiye", "swim_ow", "Jul"),
  e("Swim Serpentine", "London, UK", "swim_ow", "Sep"),
  e("Vansbrosimningen", "Vansbro, Sweden", "swim_ow", "Jul"),
];

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
export const usualMonth = (m: number) => MONTHS[m - 1];

/** Simple search: every word must appear in the name, location or type. */
export function searchEvents(q: string, limit = 8): CatalogEvent[] {
  const words = q.toLowerCase().split(/\s+/).filter(Boolean);
  if (!words.length) return [];
  return EVENTS.filter((ev) => { const hay = `${ev.name} ${ev.location} ${ev.type}`.toLowerCase(); return words.every((w) => hay.includes(w)); }).slice(0, limit);
}
